title: "Reb MD Sports Nutrition"
email: dallirebecca@gmail.com
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
formspree_contact: 'https://formspree.io/f/xnqwlpnr'
formspree_client_profile: 'https://formspree.io/f/mlekldnj'
author: Rebecca Micallef Dalli
paginate: 30
disqus: 'rebmdsportsnutrition-com'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: G-65WJS2YPX2

# Authors
authors:
  rebecca:
    name: Rebecca
    display_name: Rebecca Micallef Dalli
    avatar: 'assets/images/rebecca.jpeg'
    email: dallirebecca@gmail.com
    web: https://rebmdsportsnutrition.com/about/
    instagram: https://www.instagram.com/reb_mdsportsnutrition/
    description: "Member of the British Dietetic Association (SENR Registered), MSc. in Exercise and Nutrition Science."

# Social
social:
  instagram: https://www.instagram.com/reb_mdsportsnutrition/
  facebook: https://www.facebook.com/RebeccaMicallefDalli

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
