title: "Rebecca Micallef Dalli"
email: dallirebecca@gmail.com
timezone: UTC
baseurl: "/nutrition"
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
formspree_contact: 'https://formspree.io/f/xnqwlpnr'
author: Rebecca Dalli
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  rebecca:
    name: Rebecca
    display_name: Rebecca Micallef Dalli
    avatar: 'assets/images/rebecca.jpeg'
    email: dallirebecca@gmail.com
    web: https://rebecca.micallefdalli.com
    twitter: https://twitter.com/micallef_daniel
    description: "Member of the Association for UK Dieticians, with a M.Sc. in Exercise and Nutrition Science."

# Social
social:
  instagram: https://www.instagram.com/dallireb/
  facebook: https://www.facebook.com/RebeccaMicallefDalli

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives